<a href="https://colab.research.google.com/github/vgilton7477/Virginia-Gilton---Lab-9-NB/blob/main/Virginia_Gilton_Lab_9_NB_Lab_NaiveBayesClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Please use the iris.csv file in the DATA folder on Google Drive to perform a Naive Bayes classification.

#Virginia Giton

DSC511 - Lab 9-NB

In [1]:
#you can run this cell to mount your drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [28]:
import pandas as pd
from sklearn.model_selection import train_test_split #you will use this in the following question

#read your csv here to a dataframe called iris_df
iris_df = pd.read_csv('/content/drive/MyDrive/DATA/iris.csv')

In [29]:
# use head() to preview your dataframe
iris_df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [31]:
#Assign your dataframe to a variable called X after dropping the variety column in iris_df
#Assing your class labels to a variable called y by selecting the variety column in iris_df
#Use train_test_split function to split your X to X_train and X_test, and y to y_train and y_test. Please consider using 20% for the test set.

In [38]:
#Load Iris dataset
from sklearn import datasets
iris = datasets.load_iris()

#Assign your dataframe to a variable called X after dropping the variety column in iris_df
X = iris.data[:, :5]

#Assign your class labels to a variable called y by selecting the variety column in iris_df
y = iris.target

# Convert to DataFrame for visualization
df = pd.DataFrame(X, columns=iris.feature_names)
df["target"] = y

# Display first few rows
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

Help found in datamining - PythonScripts - SVM_iris.ipynb

Help also found in datamining - train_test_split_crossval_roc.ipynb

In [20]:
#Use train_test_split function to split your X to X_train and X_test, and y to y_train and y_test. Please consider using 20% for the test set.
# Split data into 80% training and 20% testing.

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Training set size:", X_train.shape[0])
print("Testing set size:", X_test.shape[0])

Training set size: 120
Testing set size: 30

Use the following to train your model on X_train

from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

In [58]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

data = X_train, y_train
gnb = gnb.fit(X_train, y_train)
y_pred = gnb.fit(X_train, y_train).predict(X_train)

In [60]:
print("Number of mislabeled points out of a total %d points : %d"
      % (X_train.data.shape[0],(y_train != y_pred).sum()))

Number of mislabeled points out of a total 120 points : 5

Run the following line and examine the output. Can you figure out the accuracy of the model (training accuracy) on the training set?

In [65]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train, y_pred) #make sure you have valid variables for this call

array([[40,  0,  0],
       [ 0, 38,  2],
       [ 0,  3, 37]])

Now test your model on the reserved test set, X_test and use its labels y_test to generate the same (confusion) matrix above.)

In [67]:
#you can assign your predictions for test set to y_predt based on the example above

gnb = gnb.fit(X_test, y_test)
y_predt = gnb.fit(X_test, y_test).predict(X_test)

confusion_matrix(y_test, y_predt)#make sure you have valid variables for this call

array([[10,  0,  0],
       [ 0,  9,  1],
       [ 0,  1,  9]])